language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - server/node_modules
  - client/node_modules
before_script: cd client
script:
- npm i && npm test
env:
- CI=true
before_deploy:
- npm install netlify-cli -g
- npm run build
deploy:
  - provider: script
    script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
    skip_cleanup: true
    on:
      branch: master
before_deploy:  cd ../server
deploy:
  - provider: heroku
    api_key:
      secure: hloD55GnragbZltC/qJmO5u5Xw1xm8psALEhpwWHPVTzHp2AG/r8Spevsl9Gd2QsCeH9NC3VyZLeTH/IbpDqfFHX4JgBr5FksTEAVzZkEEy4o2myuoLKdKevsrZEHBJL7KudJVDMn5zwB4d4ykD2jUsJ47favE5pxSXX4fR8enszpRe9p+mO1NMyrMh+WkROHuYtUCMHtXd0Chplrrto0h1fMUfO6Rg4tYnKgZK0SkJ/zgWsI0ASWvA2W00t8aFDVBROm7M7ZYTClUt1toL3/ixpVRKqlT8pDJB/EVyroKLLYHkIz3NuPkTGoDFbIHk9ehqi0IVOlfdCsxLySL14SruqPKxp60bS7vMQzXV93sSBCsRB4ZjNr/9HQkRu92l/2tOOPiw1iU0A7my8EAcCrNZMHtoZbDQJdvImCMkFOCJ/yoPV5OdYB+FlnYn68DHC96XpCIq5qpzOVWIfuahgLDTbPLn/gNDNP8EHYLn0jn3dNaZ1XWIK0YEAFc9jYvWNHv4nDmNRNhyB2yphD04BlvVGEkrgoWFmtZr3JoiFWHK4JcJns1K+4JuTcYyw6WRD0I+o417w4Pgk4qls5jFDWoT5OPC6KrnG34fM/OM6YnMB5YVjsWuP7anlOPhBxzeiA2ZySHPOwd/po9w3D+TGUm1nE/adyMHGZQSzFUsjI8Y=
    app: mailtroopers
    on:
      repo: johncouldbe/mailtroopers
