language: node_js
node_js:
- "6.11.3"
services:
- mongodb
cache:
  directories:
  - server/node_modules
  - client/node_modules
before_script: cd client
script:
- npm i && npm test
env:
- CI=true
before_deploy: cd ../server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "K7p2B1U0WO6JOmMqpk2GJudA6jPPSO4pgqfIxAcTqORN2pRnCrBQxbR48NHAr/1zB9TxhfkzCHLlJZHFKbWZt+OZs695kgDjMBZow4yB97m+anLGlODG21xBmYKgsenDKOutFJgz5pBdG+2SO2sKN8osM7F3KL4ak4aPdvCafqLKf470iArnnaL+owGxdmtmhwvWy70JVCRLHJao3Ppee8hTtQ8PsBQnxdhTvk/TjsLRS4Z9Y6XvcUzOaBVlPdd17q7gdBYx+HzjfZnaXtllh+kIoyXwxynV29bsUCqz79vD+v/HKDizn1KrnRdUZDPQ/uzk6F8em/jEcUhX9X8UqulY1oigkofDnV86SLjBM4MAqNDKezEdSIBjRBTDbhTG8R+BdJ9Vci1mxPqPYNmr5VL449n1Q5NSi0NLBZhVaJz0iHXW8TmUd6r25WGoPpMfThNowza2JyDZyGVDWE2fy84TWCvIDgt7Mdc1iOlyQgRzpbajDBC97keAuUvv0EMnwFJJRgyqbiqqYP1Db4aIpqSxTKj6FDS1sA0h9Y259UkQ2pcv86hzBMUXIH8aw0VpAC6UAytmGCAHAVnHjZejhsVsPYoDN4PUmdnXgdCd0x08ruBMpQ7/scnUG6Sb1x5gOk8PrKC9NSD9+QNIuNCNefgadp60C5Zw8QDM9hAZLJM="
    app: mailtroopers
  on:
    repo: johncouldbe/mailtroopers
