language: node_js
node_js:
- 6.11.3
services:
- mongodb
cache:
  directories:
  - server/node_modules
  - client/node_modules
before_script: cd client
script:
- npm i && npm test
env:
- CI=true
before_deploy: cd ../server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: tbklIbSF92uJ5YCNg/K0unz0QOUSDMKM7O7d+cn1SyzpsmqA/WwiVoMAGaspZ1EkWeH7CI2ls3FtDk5tJ/llqhTBKlFhjb6da2epBKmrVQI46OMbfJalbyGIK20EelrXj4kjulY6m4BsI7qe3BSFhSuoP/V0KKcySdd2Yz4WQpfcj2rkHV4KoxntRcQgUYJ5ngWIQyaYj3KRFtSrgX9XOu7d19/XldWN4lc16AO/PP34W8LF/1u4GDPTcDTDVgI/eNy//c+fbb9JLHCGjXXlx1DqjX5FYRQQ4EAq6Brg/z8bT+H7Bv2gpImYgYOrmCrmq47f6dm+2dJ9TmaVm99iOPEQvWzacNKBpZFfLaljffSWOEVxWNSA0hMWehYhEmL8NiRjussoThm+LnEpcqNIdgYx/WOJpnhGa+08Oq5DkPhFlX75GnDJFgRtThEgu8NEeVEFiNyJ1Suwm667kvz3F6kEp7Jv/yYp2vSWGnnu7P7l0h0sAZfiEFMHFT09UY9bxNAs9WZLbGDcfVrmsAnkyifsY5zx7tUTFI8mUMGd5SlqhROL6IRE/9qIuUqXt0Em6WSTtpokiw0EF0jO5KN+X8H6fZNVrR6J/t5FZCPq9/uIe9ZIFAtJ9OavDJznSwjftUm9plcUttWKQX7NHIrpjd905ncPsFiFYnLi18jzKlw=
  on:
    repo: johncouldbe/mailtroopers
