language: node_js
node_js:
- 6.11.3
services:
- mongodb
cache:
  directories:
  - server/node_modules
  - client/node_modules
before_script: cd client
script:
- npm i && npm test
env:
- CI=true
before_deploy: cd ../server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: fjkWoOXLrL/aMPMii1f/PGWAr2OFH/BVtxAA6ZZjxzv/kBN0/ZC/JbO1SblZljhJ5et3/z0uaqD6W+IEpjCAbrR3ife3J0HWRw5MpfOihktRKAxcW1mlwhjhqxUnAxTrMX4KsYTOnHEBNLoMbEg879Oo/harvsqY5ZKl+nitvtwOkfBKa7URoU20LJfwn9ExUW/Y6LIYzdouBwdyNRZDfucFrsEmg5CH8frUZ/uzA1lkg2PLPUAEfA1zEZx6g36gUeZPt/6Sz9WwZI6h/4kpGfkSSXZQGnZAO1iGVH29oN0SONDZ28wAc3KRZi7cML9VHGvRupIn542N6mG8idYU5f58N2hIjE/LwLuT99TX9smiBcuX9p2NxZZdFS+BUuCQLjv3/zlWL0LC+TxBYGX0YMZLN0meF7K1BVua38Tvc67KwbB54+UWkB8TVEwuhSIYjaqDbVr7o0fQgrtMjCddED2k0N4u2TFoXO6Yy+P7cf9qXnAK7dWzLD2ter1e3c6QysSLCi0hhUILkE4GcHsTqpo78bInAZCGSyMhVSHI4nN3YBZBG5QfDkoi7fwSyQd4pERF8iNYKCNgfrUU7gT+oAPTxwvzQsSbLn57zbfXLTAH2Bh6PrRc38RyXOakdojK2shV7/KZ0C6jMmZCP0zOBGC0ys/tCYdw9C4+LJqNxGc=
  on:
    repo: johncouldbe/mailtroopers
