language: node_js
node_js:
- "6.11.3"
services:
- mongodb
cache:
  directories:
  - server/node_modules
  - client/node_modules
before_script: cd client
script:
- npm i && npm test
env:
- CI=true
before_deploy: cd ../server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: skgQ/BnsBJSZJ+afc46LEoK/pbCbZjcLheR8G8n7/XBSsGMsL9SjfLvt0AL1ojtpVPAUAMVfnnc7DXNR5RrslTiUQv39vT+GkF2r7w++JaZKbTuFeFd36XuC5k5FiVWvehRhZ+2gkZTSMfU1f1C8L1r/tloTxRcL3W/hKcVHeBi9E/YmJds8Vhm81EflB/3eGW/xCsu6xG0o0hPbSnYZU6wtdreTiEl/SYyo/brP9YX0RYbI20dng8hxC22kMz8k4G21dOIDNcGVVav5eEwHUxUY1TrJqH0/XUl2iCL/De1w9WeVOhO4VmAGJ7M/hGUWhTMMZz7JPot9Y/FpAihggCEynILLb3wPZX6gfwuifsdsZwmTj2IaL6fGmOhztppYzPnfvwoSxJlYW9LSKoLZN7u0TnjcZicVBnQxSeP7tcmMjKFeyXZkBrSsvnd24rBymJjJqIDI7kkhdJMThN75xHHvC7NXNyPVDT8nZ7kogYc2rk3xGGc3tzFGdUF9MYoDSjs+e9TWxTDSlvC20VPct/lEkvblCDUTvMP1AKQzlQBiA/EkNUWQjav2VyxQK3motihnkZmPWKxYtTRktivE1kLtrBqi2ulVMk8mtxn/jko7bUdrn9GtNELImiBBmHW/bSG9IHwsWtTNGJetyGS3P4F6UQ2WLC5GnnbVMKJMong=
      app: mailtroopers
  on:
    repo: johncouldbe/mailtroopers
